// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// In an opentelemetry-collector-contrib submission this package is generated by
// mdatagen from metadata.yaml. Hand-written here to keep the module self-contained.

// Package metadata holds the component type and instrumentation-scope identifiers
// for the Guacamole receiver. In an opentelemetry-collector-contrib submission this
// package is generated by mdatagen from metadata.yaml.
package metadata

import "go.opentelemetry.io/collector/component"

// Type is the component type of the receiver.
var Type = component.MustNewType("guacamole")

const (
	// MetricsStability is the stability level of the metrics receiver.
	MetricsStability = component.StabilityLevelDevelopment

	// ScopeName is the instrumentation scope reported on emitted metrics.
	ScopeName = "github.com/guacamole-otel/guacamolereceiver"
)
